#include "sentinel/metrics/metrics.hpp"

namespace sentinel::metrics {

Metrics::Metrics(const std::string& listen_address)
    : exposer(std::make_unique<prometheus::Exposer>(listen_address)),
      registry(std::make_shared<prometheus::Registry>()),
      
      // Counters
      events_ingested_total(prometheus::BuildCounter()
          .Name("events_ingested_total")
          .Help("Total number of events ingested from RPC")
          .Register(*registry).Add({})),
      signals_normalized_total(prometheus::BuildCounter()
          .Name("signals_normalized_total")
          .Help("Total number of successfully normalized signals")
          .Register(*registry).Add({})),
      alerts_generated_total(prometheus::BuildCounter()
          .Name("alerts_generated_total")
          .Help("Total number of alerts generated by rules")
          .Register(*registry).Add({})),
      alerts_sent_total(prometheus::BuildCounter()
          .Name("alerts_sent_total")
          .Help("Total number of alerts successfully sent")
          .Register(*registry).Add({})),
      alerts_send_failures_total(prometheus::BuildCounter()
          .Name("alerts_send_failures_total")
          .Help("Total number of alert send failures")
          .Register(*registry).Add({})),
      rpc_errors_total(prometheus::BuildCounter()
          .Name("rpc_errors_total")
          .Help("Total number of RPC errors encountered")
          .Register(*registry).Add({})),

      // Gauges
      ring_buffer_depth(prometheus::BuildGauge()
          .Name("ring_buffer_depth")
          .Help("Current number of items in the main signal ring buffer")
          .Register(*registry).Add({})),
      alert_queue_depth(prometheus::BuildGauge()
          .Name("alert_queue_depth")
          .Help("Current number of items in the alert dispatcher queue")
          .Register(*registry).Add({})),
      last_rpc_success_timestamp_seconds(prometheus::BuildGauge()
          .Name("last_rpc_success_timestamp_seconds")
          .Help("Unix timestamp of the last successful RPC call")
          .Register(*registry).Add({})),
      last_alert_success_timestamp_seconds(prometheus::BuildGauge()
          .Name("last_alert_success_timestamp_seconds")
          .Help("Unix timestamp of the last successful alert send")
          .Register(*registry).Add({})),

      // Histograms
      alert_send_duration_seconds(prometheus::BuildHistogram()
          .Name("alert_send_duration_seconds")
          .Help("Time taken to send an alert across all channels")
          .Register(*registry).Add({}, prometheus::Histogram::BucketBoundaries{0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0})),
      signal_to_alert_seconds(prometheus::BuildHistogram()
          .Name("signal_to_alert_seconds")
          .Help("End-to-end latency from signal ingress to alert sent")
          .Register(*registry).Add({}, prometheus::Histogram::BucketBoundaries{0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0}))
{
    // Register the registry with the exposer
    exposer->RegisterCollectable(registry);
}

} // namespace sentinel::metrics
