#include "sentinel/metrics/metrics.hpp"

namespace sentinel::metrics {

Metrics::Metrics(const std::string& listen_address, const std::string& chain)
    : exposer(std::make_unique<prometheus::Exposer>(listen_address)),
      registry(std::make_shared<prometheus::Registry>()),
      
      // Counters
      events_ingested_total(prometheus::BuildCounter()
          .Name("events_ingested_total")
          .Help("Total number of events ingested from RPC")
          .Register(*registry)),
      signals_normalized_total(prometheus::BuildCounter()
          .Name("signals_normalized_total")
          .Help("Total number of successfully normalized signals")
          .Register(*registry)),
      alerts_generated_total(prometheus::BuildCounter()
          .Name("alerts_generated_total")
          .Help("Total number of alerts generated by rules")
          .Register(*registry)),
      alerts_sent_total(prometheus::BuildCounter()
          .Name("alerts_sent_total")
          .Help("Total number of alerts successfully sent")
          .Register(*registry)),
      alerts_send_failures_total(prometheus::BuildCounter()
          .Name("alerts_send_failures_total")
          .Help("Total number of alert send failures")
          .Register(*registry)),
      alerts_deduplicated_total(prometheus::BuildCounter()
          .Name("alerts_deduplicated_total")
          .Help("Total number of alerts suppressed by the deduplicator")
          .Register(*registry)),
      rpc_calls_total(prometheus::BuildCounter()
          .Name("rpc_calls_total")
          .Help("Total number of RPC calls made")
          .Register(*registry)),

      // Gauges
      ring_buffer_depth(prometheus::BuildGauge()
          .Name("ring_buffer_depth")
          .Help("Current number of items in the main signal ring buffer")
          .Register(*registry)),
      alert_queue_depth(prometheus::BuildGauge()
          .Name("alert_queue_depth")
          .Help("Current number of items in the alert dispatcher queue")
          .Register(*registry)),
      last_rpc_success_timestamp_seconds(prometheus::BuildGauge()
          .Name("last_rpc_success_timestamp_seconds")
          .Help("Unix timestamp of the last successful RPC call")
          .Register(*registry)),
      last_alert_success_timestamp_seconds(prometheus::BuildGauge()
          .Name("last_alert_success_timestamp_seconds")
          .Help("Unix timestamp of the last successful alert send")
          .Register(*registry)),
      last_seen_block(prometheus::BuildGauge()
          .Name("last_seen_block")
          .Help("Highest block number seen from the chain RPC")
          .Register(*registry)),
      last_processed_block(prometheus::BuildGauge()
          .Name("last_processed_block")
          .Help("Highest block number successfully processed by the system")
          .Register(*registry)),

      // Histograms
      alert_send_duration_seconds(prometheus::BuildHistogram()
          .Name("alert_send_duration_seconds")
          .Help("Time taken to send an alert across all channels")
          .Register(*registry)),
      signal_to_alert_seconds(prometheus::BuildHistogram()
          .Name("signal_to_alert_seconds")
          .Help("End-to-end latency from signal ingress to alert sent")
          .Register(*registry)),
      rpc_call_duration_seconds(prometheus::BuildHistogram()
          .Name("rpc_call_duration_seconds")
          .Help("Duration of RPC calls in seconds")
          .Register(*registry))
{
    // Register the registry with the exposer
    exposer->RegisterCollectable(registry);

    chain_name = chain;
    prometheus::Labels chain_label{{"chain", chain_name}};
    
    events_ingested_chain = &events_ingested_total.Add(chain_label);
    signals_normalized_chain = &signals_normalized_total.Add(chain_label);
    ring_buffer_depth_chain = &ring_buffer_depth.Add(chain_label);
    alert_queue_depth_chain = &alert_queue_depth.Add(chain_label);
    last_rpc_success_timestamp_seconds_chain = &last_rpc_success_timestamp_seconds.Add(chain_label);
    last_alert_success_timestamp_seconds_chain = &last_alert_success_timestamp_seconds.Add(chain_label);
    last_seen_block_chain = &last_seen_block.Add(chain_label);
    last_processed_block_chain = &last_processed_block.Add(chain_label);
}

} // namespace sentinel::metrics
